[package]
name = "godot_rust"
version = "0.1.0"
authors = ["haxeil-arch"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.9.3"
lerp = "0.4.0"
# gdnative = { path = "../../godot-rust/gdnative" }
